routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');
/*Route::get('/tail', function(){
	return view('tail');
});*/

//部署
Route::post('/deploy', 'DeployController@index')->name('deploy');
Auth::routes();

// logs
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('members', 'MembersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_templates', 'EmailTemplatesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('sending_emails', 'SendingEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_types', 'EmailTypesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('tags', 'TagsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 发送邮件
Route::get('/email_send', 'EmailSendController@create')->name('email_send.create');
Route::get('/email_send/mailgun_hook', 'EmailSendController@mailgunHook')->middleware('mailgun')->name('email_send.mailgun_hook');
Route::get('/email_send/search_member', 'EmailSendController@searchMember')->name('email_send.search_member');
Route::get('/email_send/search_product', 'EmailSendController@searchProduct')->name('email_send.search_product');
Route::any('/email_send/check_style', 'EmailSendController@checkStyle')->name('email_send.check_style');
Route::get('/email_send/retry', 'EmailSendController@retry')->name('email_send.retry');
Route::get('/email_send/retry_all', 'EmailSendController@retryAll')->name('email_send.retry_all');
Route::post('/email_send', 'EmailSendController@store')->name('email_send.store');

Route::get('/failed_jobs', 'FailedJobsController@index')->name('failed_jobs.index');
Route::get('/failed_jobs/redo', 'FailedJobsController@redo')->name('failed_jobs.redo');
Route::get('/failed_jobs/flush', 'FailedJobsController@flush')->name('failed_jobs.flush');
Route::get('/failed_jobs/{job}', 'FailedJobsController@show')->name('failed_jobs.show');
Route::delete('/failed_jobs/{job}', 'FailedJobsController@destroy')->name('failed_jobs.destroy');

Route::resource('products', 'ProductsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

Route::resource('spiders', 'SpidersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::get('/spider_cookies', 'SpidersController@cookies')->name('spider_cookies');
Route::post('/spider_cookies', 'SpidersController@storeCookies')->name('spider_cookies.store');
Route::get('/spider_log', 'SpidersController@spider_log')->name('spider_log');
Route::resource('crawl_user_emails', 'CrawlUserEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 用于爬虫执行的登录账号信息
Route::resource('spider_accounts', 'SpiderAccountsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Tag extends Model
{
    use SoftDeletes;
    
    protected $fillable = ['name'];

    protected $dates = ['deleted_at'];

    /**
     * 会员
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function members()
    {
        return $this->belongsToMany(\App\Models\Member::class, 'member_tag');
    }

}

app/Http/Controllers/TagsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\TagRequest;

class TagsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

	public function index()
	{
		$tags = Tag::paginate();
		return view('tags.index', compact('tags'));
	}

    public function show(Tag $tag)
    {
        return view('tags.show', compact('tag'));
    }

	public function create(Tag $tag)
	{
		return view('tags.create_and_edit', compact('tag'));
	}

	public function store(TagRequest $request)
	{
		$tag = Tag::create($request->all());
		return redirect()->route('tags.show', $tag->id)->with('message', 'Created successfully.');
	}

	public function edit(Tag $tag)
	{
        $this->authorize('update', $tag);
		return view('tags.create_and_edit', compact('tag'));
	}

	public function update(TagRequest $request, Tag $tag)
	{
		$this->authorize('update', $tag);
		$tag->update($request->all());

		return redirect()->route('tags.show', $tag->id)->with('message', 'Updated successfully.');
	}

	public function destroy(Tag $tag)
	{
		$this->authorize('destroy', $tag);
		$tag->delete();

		return redirect()->route('tags.index')->with('message', 'Deleted successfully.');
	}
}

resources/views/tags/create_and_edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                <h1>
                    <i class="glyphicon glyphicon-edit"></i> Tag /
                    @if($tag->id)
                        Edit #{{$tag->id}}
                    @else
                        Create
                    @endif
                </h1>
            </div>

            @include('common.error')

            <div class="panel-body">
                @if($tag->id)
                    <form action="{{ route('tags.update', $tag->id) }}" method="POST" accept-charset="UTF-8">
                        <input type="hidden" name="_method" value="PUT">
                @else
                    <form action="{{ route('tags.store') }}" method="POST" accept-charset="UTF-8">
                @endif

                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    
                <div class="form-group">
                	<label for="name-field">Name</label>
                	<input class="form-control" type="text" name="name" id="name-field" value="{{ old('name', $tag->name ) }}" />
                </div>

                    <div class="well well-sm">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-link pull-right" href="{{ route('tags.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/tags/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>
                    <i class="glyphicon glyphicon-align-justify"></i> Tag
                    <a class="btn btn-success pull-right" href="{{ route('tags.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
                </h1>
            </div>

            <div class="panel-body">
                @if($tags->count())
                    <table class="table table-condensed table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th>Name</th>
                                <th class="text-right">OPTIONS</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($tags as $tag)
                                <tr>
                                    <td class="text-center"><strong>{{$tag->id}}</strong></td>

                                    <td>{{$tag->name}}</td>
                                    
                                    <td class="text-right">
                                        <a class="btn btn-xs btn-primary" href="{{ route('tags.show', $tag->id) }}">
                                            <i class="glyphicon glyphicon-eye-open"></i> 
                                        </a>
                                        
                                        <a class="btn btn-xs btn-warning" href="{{ route('tags.edit', $tag->id) }}">
                                            <i class="glyphicon glyphicon-edit"></i> 
                                        </a>

                                        <form action="{{ route('tags.destroy', $tag->id) }}" method="POST" style="display: inline;" onsubmit="return confirm('Delete? Are you sure?');">
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE">

                                            <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {!! $tags->render() !!}
                @else
                    <h3 class="text-center alert alert-info">Empty!</h3>
                @endif
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/tags/show.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>Tag / Show #{{ $tag->id }}</h1>
            </div>

            <div class="panel-body">
                <div class="well well-sm">
                    <div class="row">
                        <div class="col-md-6">
                            <a class="btn btn-link" href="{{ route('tags.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                        </div>
                        <div class="col-md-6">
                             <a class="btn btn-sm btn-warning pull-right" href="{{ route('tags.edit', $tag->id) }}">
                                <i class="glyphicon glyphicon-edit"></i> Edit
                            </a>
                        </div>
                    </div>
                </div>

                <label>Name</label>
<p>
	{{ $tag->name }}
</p>
            </div>
        </div>
    </div>
</div>

@endsection