routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');
/*Route::get('/tail', function(){
	return view('tail');
});*/

//部署
Route::post('/deploy', 'DeployController@index')->name('deploy');
Auth::routes();

// logs
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('members', 'MembersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_templates', 'EmailTemplatesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('sending_emails', 'SendingEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_types', 'EmailTypesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('tags', 'TagsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 发送邮件
Route::get('/email_send', 'EmailSendController@create')->name('email_send.create');
Route::get('/email_send/mailgun_hook', 'EmailSendController@mailgunHook')->middleware('mailgun')->name('email_send.mailgun_hook');
Route::get('/email_send/search_member', 'EmailSendController@searchMember')->name('email_send.search_member');
Route::get('/email_send/search_product', 'EmailSendController@searchProduct')->name('email_send.search_product');
Route::any('/email_send/check_style', 'EmailSendController@checkStyle')->name('email_send.check_style');
Route::get('/email_send/retry', 'EmailSendController@retry')->name('email_send.retry');
Route::get('/email_send/retry_all', 'EmailSendController@retryAll')->name('email_send.retry_all');
Route::post('/email_send', 'EmailSendController@store')->name('email_send.store');

Route::get('/failed_jobs', 'FailedJobsController@index')->name('failed_jobs.index');
Route::get('/failed_jobs/redo', 'FailedJobsController@redo')->name('failed_jobs.redo');
Route::get('/failed_jobs/flush', 'FailedJobsController@flush')->name('failed_jobs.flush');
Route::get('/failed_jobs/{job}', 'FailedJobsController@show')->name('failed_jobs.show');
Route::delete('/failed_jobs/{job}', 'FailedJobsController@destroy')->name('failed_jobs.destroy');

Route::resource('products', 'ProductsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

Route::resource('spiders', 'SpidersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::get('/spider_cookies', 'SpidersController@cookies')->name('spider_cookies');
Route::post('/spider_cookies', 'SpidersController@storeCookies')->name('spider_cookies.store');
Route::get('/spider_log', 'SpidersController@spider_log')->name('spider_log');
Route::resource('crawl_user_emails', 'CrawlUserEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 用于爬虫执行的登录账号信息
Route::resource('spider_accounts', 'SpiderAccountsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

app/Http/Controllers/EmailTypesController.php
<?php

namespace App\Http\Controllers;

use App\Models\EmailType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\EmailTypeRequest;

class EmailTypesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

	public function index()
	{
		$email_types = EmailType::paginate();
		return view('email_types.index', compact('email_types'));
	}

    public function show(EmailType $email_type)
    {
        return view('email_types.show', compact('email_type'));
    }

	public function create(EmailType $email_type)
	{
		return view('email_types.create_and_edit', compact('email_type'));
	}

	public function store(EmailTypeRequest $request)
	{
		$email_type = EmailType::create($request->all());
		return redirect()->route('email_types.show', $email_type->id)->with('message', 'Created successfully.');
	}

	public function edit(EmailType $email_type)
	{
        $this->authorize('update', $email_type);
		return view('email_types.create_and_edit', compact('email_type'));
	}

	public function update(EmailTypeRequest $request, EmailType $email_type)
	{
		$this->authorize('update', $email_type);
		$email_type->update($request->all());

		return redirect()->route('email_types.show', $email_type->id)->with('message', 'Updated successfully.');
	}

	public function destroy(EmailType $email_type)
	{
		$this->authorize('destroy', $email_type);
		$email_type->delete();

		return redirect()->route('email_types.index')->with('message', 'Deleted successfully.');
	}
}

resources/views/email_types/create_and_edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                <h1>
                    <i class="glyphicon glyphicon-edit"></i> EmailType /
                    @if($email_type->id)
                        Edit #{{$email_type->id}}
                    @else
                        Create
                    @endif
                </h1>
            </div>

            @include('common.error')

            <div class="panel-body">
                @if($email_type->id)
                    <form action="{{ route('email_types.update', $email_type->id) }}" method="POST" accept-charset="UTF-8">
                        <input type="hidden" name="_method" value="PUT">
                @else
                    <form action="{{ route('email_types.store') }}" method="POST" accept-charset="UTF-8">
                @endif

                    <input type="hidden" name="_token" value="{{ csrf_token() }}">

                    
                <div class="form-group">
                	<label for="name-field">Name</label>
                	<input class="form-control" type="text" name="name" id="name-field" value="{{ old('name', $email_type->name ) }}" />
                </div>

                    <div class="well well-sm">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-link pull-right" href="{{ route('email_types.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/email_types/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>
                    <i class="glyphicon glyphicon-align-justify"></i> EmailType
                    <a class="btn btn-success pull-right" href="{{ route('email_types.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
                </h1>
            </div>

            <div class="panel-body">
                @if($email_types->count())
                    <table class="table table-condensed table-striped">
                        <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th>Name</th>
                                <th class="text-right">OPTIONS</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($email_types as $email_type)
                                <tr>
                                    <td class="text-center"><strong>{{$email_type->id}}</strong></td>

                                    <td>{{$email_type->name}}</td>
                                    
                                    <td class="text-right">
                                        <a class="btn btn-xs btn-primary" href="{{ route('email_types.show', $email_type->id) }}">
                                            <i class="glyphicon glyphicon-eye-open"></i> 
                                        </a>
                                        
                                        <a class="btn btn-xs btn-warning" href="{{ route('email_types.edit', $email_type->id) }}">
                                            <i class="glyphicon glyphicon-edit"></i> 
                                        </a>

                                        <form action="{{ route('email_types.destroy', $email_type->id) }}" method="POST" style="display: inline;" onsubmit="return confirm('Delete? Are you sure?');">
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE">

                                            <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {!! $email_types->render() !!}
                @else
                    <h3 class="text-center alert alert-info">Empty!</h3>
                @endif
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/email_types/show.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>EmailType / Show #{{ $email_type->id }}</h1>
            </div>

            <div class="panel-body">
                <div class="well well-sm">
                    <div class="row">
                        <div class="col-md-6">
                            <a class="btn btn-link" href="{{ route('email_types.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                        </div>
                        <div class="col-md-6">
                             <a class="btn btn-sm btn-warning pull-right" href="{{ route('email_types.edit', $email_type->id) }}">
                                <i class="glyphicon glyphicon-edit"></i> Edit
                            </a>
                        </div>
                    </div>
                </div>

                <label>Name</label>
<p>
	{{ $email_type->name }}
</p>
            </div>
        </div>
    </div>
</div>

@endsection