routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');
/*Route::get('/tail', function(){
	return view('tail');
});*/

//部署
Route::post('/deploy', 'DeployController@index')->name('deploy');
Auth::routes();

// logs
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('members', 'MembersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_templates', 'EmailTemplatesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('sending_emails', 'SendingEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_types', 'EmailTypesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('tags', 'TagsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 发送邮件
Route::get('/email_send', 'EmailSendController@create')->name('email_send.create');
Route::get('/email_send/mailgun_hook', 'EmailSendController@mailgunHook')->middleware('mailgun')->name('email_send.mailgun_hook');
Route::get('/email_send/search_member', 'EmailSendController@searchMember')->name('email_send.search_member');
Route::get('/email_send/search_product', 'EmailSendController@searchProduct')->name('email_send.search_product');
Route::any('/email_send/check_style', 'EmailSendController@checkStyle')->name('email_send.check_style');
Route::get('/email_send/retry', 'EmailSendController@retry')->name('email_send.retry');
Route::get('/email_send/retry_all', 'EmailSendController@retryAll')->name('email_send.retry_all');
Route::post('/email_send', 'EmailSendController@store')->name('email_send.store');

Route::get('/failed_jobs', 'FailedJobsController@index')->name('failed_jobs.index');
Route::get('/failed_jobs/redo', 'FailedJobsController@redo')->name('failed_jobs.redo');
Route::get('/failed_jobs/flush', 'FailedJobsController@flush')->name('failed_jobs.flush');
Route::get('/failed_jobs/{job}', 'FailedJobsController@show')->name('failed_jobs.show');
Route::delete('/failed_jobs/{job}', 'FailedJobsController@destroy')->name('failed_jobs.destroy');

Route::resource('products', 'ProductsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

Route::resource('spiders', 'SpidersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::get('/spider_cookies', 'SpidersController@cookies')->name('spider_cookies');
Route::post('/spider_cookies', 'SpidersController@storeCookies')->name('spider_cookies.store');
Route::get('/spider_log', 'SpidersController@spider_log')->name('spider_log');
Route::resource('crawl_user_emails', 'CrawlUserEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 用于爬虫执行的登录账号信息
Route::resource('spider_accounts', 'SpiderAccountsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

app/Models/EmailTemplate.php
<?php

namespace App\Models;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\EmailTemplate
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Model ordered()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Model recent()
 * @mixin \Eloquent
 */
class EmailTemplate extends Model
{
    use SoftDeletes;

    protected $fillable = ['id', 'name', 'content', 'type_id'];

    protected $dates = ['deleted_at'];

    /**
     * Mails
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function emails()
    {
        return $this->hasMany(\App\Models\SendingEmail::class, 'email_template_id');
    }

    /**
     * type 类型
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function type()
    {
        return $this->belongsTo(\App\Models\EmailType::class, 'type_id', 'id');
    }
    

    /**
     * 使用该模板发送邮件的会员信息
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function members()
    {
        return $this->belongsToMany(\App\Models\Member::class, 'sending_emails', 'email_template_id', 'member_id');
    }
}

app/Http/Controllers/EmailTemplatesController.php
<?php

namespace App\Http\Controllers;

use App\Models\EmailTemplate;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\EmailTemplateRequest;

class EmailTemplatesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

    public function index()
    {
        $email_templates = EmailTemplate::with('type')->withCount('emails')->paginate();

        return view('email_templates.index', compact('email_templates'));
    }

    public function show(EmailTemplate $email_template)
    {
        $result = EmailTemplate::with('type')->withCount('emails')->find($email_template);
        dd($result->toArray());
        return view('email_templates.show', compact('email_template'));
    }

    public function create(EmailTemplate $email_template)
    {
        return view('email_templates.create_and_edit', compact('email_template'));
    }

    public function store(EmailTemplateRequest $request)
    {
        $email_template = EmailTemplate::create($request->all());

        return redirect()->route('email_templates.show', $email_template->id)->with('message', 'Created successfully.');
    }

    public function edit(EmailTemplate $email_template)
    {
        $this->authorize('update', $email_template);

        return view('email_templates.create_and_edit', compact('email_template'));
    }

    public function update(EmailTemplateRequest $request, EmailTemplate $email_template)
    {
        $this->authorize('update', $email_template);
        $email_template->update($request->all());

        return redirect()->route('email_templates.show', $email_template->id)->with('message', 'Updated successfully.');
    }

    public function destroy(EmailTemplate $email_template)
    {
        $this->authorize('destroy', $email_template);
        $email_template->delete();

        return redirect()->route('email_templates.index')->with('message', 'Deleted successfully.');
    }
}

resources/views/email_templates/create_and_edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">

            <div class="panel-heading">
                <h1>
                    <i class="glyphicon glyphicon-edit"></i> EmailTemplate /
                    @if($email_template->id)
                        Edit #{{$email_template->id}}
                    @else
                        Create
                    @endif
                </h1>
            </div>

            @include('common.error')

            <div class="panel-body">
                @if($email_template->id)
                    <form action="{{ route('email_templates.update', $email_template->id) }}" method="POST" accept-charset="UTF-8">
                        <input type="hidden" name="_method" value="PUT">
                @else
                    <form action="{{ route('email_templates.store') }}" method="POST" accept-charset="UTF-8">
                @endif

                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group">
                	<label for="name-field">Name</label>
                	<input class="form-control" type="text" name="name" id="name-field" value="{{ old('name', $email_template->name ) }}" />
                </div>
                <div class="form-group">
                    <label for="type_id-field">Type</label>
                    <input class="form-control" type="text" name="type_id" id="type_id-field" value="{{ old('type_id', $email_template->type_id ) }}" />
                </div>
                <div class="form-group">
                    <label for="class_name-field">ClassName</label>
                    <input class="form-control" type="text" name="class_name" id="class_name-field" value="{{ old('class_name', $email_template->class_name ) }}" />
                </div>
                {!! we_css() !!}
                {!! we_js() !!}
                <div class="form-group">
                	<label for="content-field">Content</label>
                    {!! we_field('wangeditor', 'content', old('name', $email_template->content )) !!}
                    {!! we_config('wangeditor') !!}
                </div>
                    <div class="well well-sm">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-success" target="_blank"
                           href="{{ route('email_send.check_style', ['template_id'=> $email_template->id , 'member_ids' => 1, 'product_ids' => 1]) }}">
                            查看样式
                        </a>
                        <a class="btn btn-link pull-right" href="{{ route('email_templates.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/email_templates/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="col-md-10">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1>
                        <i class="glyphicon glyphicon-align-justify"></i> EmailTemplate
                        <a class="btn btn-success pull-right" href="{{ route('email_templates.create') }}"><i
                                    class="glyphicon glyphicon-plus"></i> Create</a>
                    </h1>
                </div>

                <div class="panel-body">
                    @if($email_templates->count())
                        <table class="table table-condensed table-striped">
                            <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th>Name</th>
                                <th>TypeId</th>
                                <th>EmailSum</th>
                                <th>ClassName</th>
                                <th>CreatedAt</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($email_templates as $email_template)
                                <tr>
                                    <td class="text-center"><strong>{{$email_template->id}}</strong></td>

                                    <td>{{$email_template->name}}</td>
                                    <td>{{$email_template->type_id .'|'.$email_template->type->name}}</td>
                                    <td>{{$email_template->emails_count}}</td>
                                    <td>{{$email_template->class_name}}</td>
                                    <td>{{$email_template->created_at}}</td>

                                    {{--<td class="text-right">
                                        <a class="btn btn-xs btn-primary"
                                           href="{{ route('email_templates.show', $email_template->id) }}">
                                            <i class="glyphicon glyphicon-eye-open"></i>
                                        </a>

                                        <a class="btn btn-xs btn-warning"
                                           href="{{ route('email_templates.edit', $email_template->id) }}">
                                            <i class="glyphicon glyphicon-edit"></i>
                                        </a>

                                        <form action="{{ route('email_templates.destroy', $email_template->id) }}"
                                              method="POST" style="display: inline;"
                                              onsubmit="return confirm('Delete? Are you sure?');">
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE">

                                            <button type="submit" class="btn btn-xs btn-danger"><i
                                                        class="glyphicon glyphicon-trash"></i></button>
                                        </form>
                                    </td>--}}
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {!! $email_templates->render() !!}
                    @else
                        <h3 class="text-center alert alert-info">Empty!</h3>
                    @endif
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/email_templates/show.blade.php
@extends('layouts.admin')

@section('content')

    <div class="container">
        <div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1>EmailTemplate / Show #{{ $email_template->id }}</h1>
                </div>

                <div class="panel-body">
                    <div class="well well-sm">
                        <div class="row">
                            <div class="col-md-6">
                                <a class="btn btn-link" href="{{ route('email_templates.index') }}"><i
                                            class="glyphicon glyphicon-backward"></i> Back</a>
                            </div>
                            <div class="col-md-6">
                                <a class="btn btn-sm btn-warning pull-right"
                                   href="{{ route('email_templates.edit', $email_template->id) }}">
                                    <i class="glyphicon glyphicon-edit"></i> Edit
                                </a>
                            </div>
                        </div>
                    </div>

                    <input type="hidden" id="template_id" value="{{ $email_template->id }}">
                    <label>Name</label>
                    <p>
                        {{ $email_template->name }}
                    </p> <label>ClassName</label>
                    <p>
                        {!! old('class_name', $email_template->class_name ) !!}
                    </p>
                    <label>模板</label>
                    <div id="template">

                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('js')
<script>
  $(function(){
    loadTemplate();
  });

  function loadTemplate() {
    $.ajax({
      url: '/email_send/check_style',
      type: 'POST',
      data: {
        member_ids: '1',
        product_ids: '1',
        template_id: $('#template_id').val()
      },
      success: function (response) {
        $('#template').html(response)
      },
      dataType: 'html'
    });
  }
</script>
@endpush