routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@welcome');
/*Route::get('/tail', function(){
	return view('tail');
});*/

//部署
Route::post('/deploy', 'DeployController@index')->name('deploy');
Auth::routes();

// logs
Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->middleware('auth');

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('members', 'MembersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_templates', 'EmailTemplatesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('sending_emails', 'SendingEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('email_types', 'EmailTypesController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::resource('tags', 'TagsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 发送邮件
Route::get('/email_send', 'EmailSendController@create')->name('email_send.create');
Route::get('/email_send/mailgun_hook', 'EmailSendController@mailgunHook')->middleware('mailgun')->name('email_send.mailgun_hook');
Route::get('/email_send/search_member', 'EmailSendController@searchMember')->name('email_send.search_member');
Route::get('/email_send/search_product', 'EmailSendController@searchProduct')->name('email_send.search_product');
Route::any('/email_send/check_style', 'EmailSendController@checkStyle')->name('email_send.check_style');
Route::get('/email_send/retry', 'EmailSendController@retry')->name('email_send.retry');
Route::get('/email_send/retry_all', 'EmailSendController@retryAll')->name('email_send.retry_all');
Route::post('/email_send', 'EmailSendController@store')->name('email_send.store');

Route::get('/failed_jobs', 'FailedJobsController@index')->name('failed_jobs.index');
Route::get('/failed_jobs/redo', 'FailedJobsController@redo')->name('failed_jobs.redo');
Route::get('/failed_jobs/flush', 'FailedJobsController@flush')->name('failed_jobs.flush');
Route::get('/failed_jobs/{job}', 'FailedJobsController@show')->name('failed_jobs.show');
Route::delete('/failed_jobs/{job}', 'FailedJobsController@destroy')->name('failed_jobs.destroy');

Route::resource('products', 'ProductsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

Route::resource('spiders', 'SpidersController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);
Route::get('/spider_cookies', 'SpidersController@cookies')->name('spider_cookies');
Route::post('/spider_cookies', 'SpidersController@storeCookies')->name('spider_cookies.store');
Route::get('/spider_log', 'SpidersController@spider_log')->name('spider_log');
Route::resource('crawl_user_emails', 'CrawlUserEmailsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

// 用于爬虫执行的登录账号信息
Route::resource('spider_accounts', 'SpiderAccountsController', ['only' => ['index', 'show', 'create', 'store', 'update', 'edit', 'destroy']]);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    public $dates = ['deleted_at'];

    protected $fillable = ['sku','name', 'desc', 'price', 'promotion_price', 'picture_url', 'link_url', 'notes'];

    /**
     * 邮件
     *
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function emails()
    {
        return $this->belongsToMany(\App\Models\SendingEmail::class, 'email_product', 'product_id', 'email_id');
    }
}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use Maatwebsite\Excel\Facades\Excel;

class ProductsController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => ['index', 'show']]);
    }

	public function index(ProductRequest $request)
	{
        $where = [];
        if ($skuStr = $request->sku) {
            //$skuArr = explode(',', $skuStr);
            $where['sku']= $skuStr;
        }
        if ($name = $request->name) {
            $where[] = ['name', 'like', '%' . $name . '%'];
        }
		$products = Product::withCount('emails')->where($where)->recent()->paginate(50);
        $products->appends(['name' => $name, 'sku'=> $skuStr]);

		return view('products.index', compact('products'));
	}

    public function show(Product $product)
    {
        return view('products.show', compact('product'));
    }

	public function create(Product $product)
	{
		return view('products.create_and_edit', compact('product'));
	}

	public function store(ProductRequest $request)
	{
        if ($request->excel) {
            return $this->import($request);
        }
		$product = Product::create($request->all());
		return redirect()->route('products.show', $product->id)->with('message', 'Created successfully.');
	}

	public function edit(Product $product)
	{
        $this->authorize('update', $product);
		return view('products.create_and_edit', compact('product'));
	}

	public function update(ProductRequest $request, Product $product)
	{
		$this->authorize('update', $product);
		$product->update($request->all());

		return redirect()->route('products.show', $product->id)->with('message', 'Updated successfully.');
	}

	public function destroy(Product $product)
	{
		$this->authorize('destroy', $product);
		$product->delete();

		return redirect()->route('products.index')->with('message', 'Deleted successfully.');
	}

    private function import(Request $request)
    {
        $this->validate($request, ['file' => 'required']);

        try {
            Excel::load($request->file('file'), function ($reader) {
                foreach ($reader->toArray() as $row) {
                    Product::firstOrCreate($row);
                }
            });
            \Session::flash('success', 'Products uploaded successfully.');
        } catch (\Exception $e) {
            \Session::flash('error', $e->getMessage());
        }
        return redirect(route('products.index'));
    }
}

resources/views/products/create_and_edit.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            
            <div class="panel-heading">
                <h1>
                    <i class="glyphicon glyphicon-edit"></i> Product /
                    @if($product->id)
                        Edit #{{$product->id}}
                    @else
                        Create
                    @endif
                </h1>
            </div>

            @include('common.error')

            <div class="panel-body">
                @if($product->id)
                    <form action="{{ route('products.update', $product->id) }}" method="POST" accept-charset="UTF-8">
                        <input type="hidden" name="_method" value="PUT">
                @else
                    <form action="{{ route('products.store') }}" method="POST" accept-charset="UTF-8">
                @endif

                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                <div class="form-group">
                	<label for="sku-field">SKU</label>
                	<input class="form-control" type="text" name="sku" id="sku-field" value="{{ old('sku', $product->name ) }}" />
                </div>
                <div class="form-group">
                	<label for="name-field">Name</label>
                	<input class="form-control" type="text" name="name" id="name-field" value="{{ old('name', $product->name ) }}" />
                </div>
                <div class="form-group">
                	<label for="desc-field">Desc</label>
                	<input class="form-control" type="text" name="desc" id="desc-field" value="{{ old('desc', $product->desc ) }}" />
                </div> 
                <div class="form-group">
                    <label for="price-field">Price</label>
                    <input class="form-control" type="text" name="price" id="price-field" value="{{ old('price', $product->price ) }}" />
                </div> 
                <div class="form-group">
                    <label for="promotion_price-field">Promotion_price</label>
                    <input class="form-control" type="text" name="promotion_price" id="promotion_price-field" value="{{ old('promotion_price', $product->promotion_price ) }}" />
                </div> 
                <div class="form-group">
                	<label for="picture_url-field">Picture_url</label>
                	<input class="form-control" type="text" name="picture_url" id="picture_url-field" value="{{ old('picture_url', $product->picture_url ) }}" />
                </div> 
                <div class="form-group">
                	<label for="link_url-field">Link_url</label>
                	<input class="form-control" type="text" name="link_url" id="link_url-field" value="{{ old('link_url', $product->link_url ) }}" />
                </div> 
                <div class="form-group">
                	<label for="notes-field">Notes</label>
                    <textarea class="form-control" name="notes" id="notes-field" cols="30" rows="3">{{ old('notes', $product->notes ) }}</textarea>
                </div>

                    <div class="well well-sm">
                        <button type="submit" class="btn btn-primary">Save</button>
                        <a class="btn btn-link pull-right" href="{{ route('products.index') }}"><i class="glyphicon glyphicon-backward"></i>  Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/products/index.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>
                    <i class="glyphicon glyphicon-align-justify"></i> Product
                    <a class="btn btn-success pull-right" href="{{ route('products.create') }}"><i class="glyphicon glyphicon-plus"></i> Create</a>
                </h1>
                @component('_partial.import', ['template_url' => '/excel/products_template.xlsx', 'action' => route('products.store', ['excel'=>1])])
                @endcomponent
            </div>

            <div class="panel-body">
                <form class="form-inline" action="{{route('products.index')}}">
                    <div class="form-group">
                        <label for="search-sku">Asin</label>
                        <input type="text" class="form-control" name="sku" id="search-sku" value="{{ request('sku') }}" placeholder="sku">
                    </div>
                    <div class="form-group">
                        <label for="search-name">Name</label>
                        <input type="text" class="form-control" name="name" id="search-name" value="{{ request('name') }}" placeholder="name">
                    </div>
                    <button type="submit" class="btn btn-primary pull-right"><i class="glyphicon glyphicon-search"></i> Search</button>
                </form>
                @if($products->count())
                    <div class="table-responsive">
                        <table class="table table-condensed table-striped">
                            <thead>
                            <tr>
                                <th class="text-center">#</th>
                                <th>SKU</th>
                                <th>EmailCount</th>
                                <th>Name</th>
                                <th>Desc</th>
                                <th>Price</th>
                                <th>Promotion_price</th>
                                <th>Picture_url</th>
                                <th>Link_url</th>
                                <th>Notes</th>
                                <th class="text-right">OPTIONS</th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($products as $product)
                                <tr>
                                    <td class="text-center"><strong>{{$product->id}}</strong></td>

                                    <td>{{$product->sku}}</td>
                                    <td>{{$product->emails_count}}</td>
                                    <td>{{$product->name}}</td>
                                    <td>{{ \Illuminate\Support\Str::words($product->desc, 20) }}</td>
                                    <td>${{$product->price}}</td>
                                    <td>${{$product->promotion_price}}</td>
                                    <td><img src="{{$product->picture_url}}" style="height: 50px"></td>
                                    <td><a href="{{$product->link_url}}" target="_blank">商品链接</a></td>
                                    <td>{{ \Illuminate\Support\Str::words($product->notes, 20) }}</td>

                                    <td class="text-right">
                                        <a class="btn btn-xs btn-primary" href="{{ route('products.show', $product->id) }}">
                                            <i class="glyphicon glyphicon-eye-open"></i>
                                        </a>

                                        <a class="btn btn-xs btn-warning" href="{{ route('products.edit', $product->id) }}">
                                            <i class="glyphicon glyphicon-edit"></i>
                                        </a>

                                        <form action="{{ route('products.destroy', $product->id) }}" method="POST" style="display: inline;" onsubmit="return confirm('Delete? Are you sure?');">
                                            {{csrf_field()}}
                                            <input type="hidden" name="_method" value="DELETE">

                                            <button type="submit" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-trash"></i> </button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {!! $products->render() !!}
                    </div>
                @else
                    <h3 class="text-center alert alert-info">Empty!</h3>
                @endif
            </div>
        </div>
    </div>
</div>

@endsection

resources/views/products/show.blade.php
@extends('layouts.admin')

@section('content')

<div class="container">
    <div class="col-md-10">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h1>Product / Show #{{ $product->id }}</h1>
            </div>

            <div class="panel-body">
                <div class="well well-sm">
                    <div class="row">
                        <div class="col-md-6">
                            <a class="btn btn-link" href="{{ route('products.index') }}"><i class="glyphicon glyphicon-backward"></i> Back</a>
                        </div>
                        <div class="col-md-6">
                             <a class="btn btn-sm btn-warning pull-right" href="{{ route('products.edit', $product->id) }}">
                                <i class="glyphicon glyphicon-edit"></i> Edit
                            </a>
                        </div>
                    </div>
                </div>

                <label>SKU</label>
<p>
	{{ $product->sku }}
</p>
                <label>Name</label>
                <p>
                    {{ $product->name }}
                </p>
                <label>Desc</label>
<p>
	{{ $product->desc }}
</p> <label>Price</label>
<p>
	{{ $product->price }}
</p> <label>Promotion_price</label>
<p>
	{{ $product->promotion_price }}
</p> <label>Picture_url</label>
<p>
    <img src="{{ $product->picture_url }}">
</p> <label>Link_url</label>
<p>
	{{ $product->link_url }}
</p> <label>Notes</label>
<p>
	{{ $product->notes }}
</p>
            </div>
        </div>
    </div>
</div>

@endsection